services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"

  notifier:
    container_name: notifier
    build: ./notifier
    platform: linux/amd64
    image: ghcr.io/jotpalch/portcdm-notifier
    depends_on:
      - db
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      LINE_NOTIFY_TOKEN: ${LINE_NOTIFY_TOKEN}
      LINE_NOTIFY_TOKEN_PILOT: ${LINE_NOTIFY_TOKEN_PILOT}
      LINE_NOTIFY_TOKEN_UNMOORING: ${LINE_NOTIFY_TOKEN_UNMOORING}
      LINE_NOTIFY_TOKEN_TUGBOAT: ${LINE_NOTIFY_TOKEN_TUGBOAT}
      LINE_NOTIFY_TOKEN_SHIPPINGAGENT: ${LINE_NOTIFY_TOKEN_SHIPPINGAGENT}
      LINE_NOTIFY_TOKEN_SHIPPINGCOMPANY: ${LINE_NOTIFY_TOKEN_SHIPPINGCOMPANY}
      LINE_NOTIFY_TOKEN_LOADINGUNLOADING: ${LINE_NOTIFY_TOKEN_LOADINGUNLOADING}
      INTERVAL_TIME: ${INTERVAL_TIME}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "main.py"]

  crawler:
    container_name: crawler
    build: ./crawler
    platform: linux/amd64
    image: ghcr.io/jotpalch/portcdm-crawler
    depends_on:
      - notifier
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      INTERVAL_TIME: ${INTERVAL_TIME}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./output:/app/output
    
volumes:
  postgres_data:
    name: postgres_db
